# -------- Stage 1: Build Layer --------
FROM node:20-alpine AS build

WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./

#--omit=dev Means Don't install devDependencies — only install dependencies
RUN npm install --omit=dev

# Copy app source code
COPY . .

# -------- Stage 2: Final Minimal Layer --------
FROM node:20-alpine

WORKDIR /usr/src/app

# Copy built app and node_modules from build stage
COPY --from=build /usr/src/app ./

EXPOSE 4011

CMD ["node", "index.js"]
    